-- Supabase SQL (run in SQL Editor)
create table if not exists public.waitlist (
  id bigint generated by default as identity primary key,
  email text not null,
  industry text,
  team_size text,
  source text,
  created_at timestamptz not null default now()
);

-- Ensure upsert works and prevents duplicates
create unique index if not exists waitlist_email_key on public.waitlist (email);

-- If you decide to insert from the browser using an anon key (NOT service role),
-- enable RLS + add an insert policy like below.
-- alter table public.waitlist enable row level security;
-- create policy "Allow public inserts" on public.waitlist
--   for insert to anon
--   with check (true);
